name = "practice-hono"
main = "src/index.ts"
compatibility_date = "2024-10-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hono-pracctice"
database_id = "006a54eb-b6be-4882-8642-07bc62a3dfca"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1